### ISSUE TITLE
There are two little bugs.

### ISSUE THREAD

**Issue by atfa** [hellodeibu/gpd-pocket2-hackintosh#1]
I successfully install Macos Mojave into my GPD Pocket 2 using your EFI. Thanks a lot.
There are 2 little bugs.
1. I know the sleep mode cannot work. But how to disable sleep mode ? When I close the lid, the Macos automatically sleep. So when I open the lid, the screen is blank. The only operation I can do is " long press " the power botton.

2. The Bluetooth cannot connect to my mouse. And I cannot find how to turn off the Bluetooth.

**Comment by bertiepeek** [comment]
Yes I can't wake from sleep either without restarting the whole machine! Is there a fix for this?

**Comment by jibsaram** [comment]
@atfa @bertiepeek apologies for the late reply, I've had a busy month. A fix _should_ be possible yes. The device actually sleeps and wakes properly the first time, it is only the display that refuses to turn on again (you can verify this by using screen sharing from another device, for example).

The current method to get the internal display to work is decidedly hacky and messy, which I suspect is the culprit here. There might also be something we have to do to more correctly implement brightness adjustment functionality, as that's commonly referred to when people have the same issue we have on other devices, but I am not sure on that just yet.

I just pushed an update that should give us properly configured/assigned USB ports, which is another thing that at times causes sleep/wake issues. At least that's out of the way, so to speak, but we'll have to fiddle more to get sleep fully working.

**Edit:** Forgot to add: What might help here is to make and patch a new DSDT file. Maybe that's a good place to start.
