### ISSUE TITLE
Some Bluetooth devices cannot pair, some can.

### ISSUE THREAD

**Issue by glowingkitty** [hellodeibu/gpd-pocket2-hackintosh#11]
While my keyboard and headset can connect perfectly fine via Bluetooth - when I connect my Bluetooth mouse I end up with an infinite connecting loading wheel. Any suggestions how to improve the Bluetooth support? Any specific drivers?

**Comment by jibsaram** [comment]
I discovered that my notifications for this repository were somehow disabled, so I'm only now getting around to this. I hope by now you have already resolved or otherwise found a way around this issue, but either way; I've stopped using Hackintoshes years ago now, and no longer have the Pocket 2, so I'm afraid I can't help you. If you still have this or other issues, I'd advice looking for a relevant Reddit or Discord community and asking for help there. Sorry I can't be of more use!
