### ISSUE TITLE
GPD Pocket 2 Celeron 3965Y

### ISSUE THREAD

**Issue by devisucarmelo** [hellodeibu/gpd-pocket2-hackintosh#24]
Hello,
on my GPD 2 the boot procedure gets stuck right after the Clover boot selection. It shows the Apple logo and a kinda little scroll bar on the left side of the screen.
Tried with both Mojave and Catalina RAW images.
![IMG_5748](https://user-images.githubusercontent.com/128718971/227249260-27a049cb-95e6-4593-8250-3d3beca9d59e.jpeg)

**Comment by jibsaram** [comment]
I'm afraid I won't be able to help you much as I've stopped using Hackintoshes (and no longer have a Pocket 2), so you might be better off asking for help in a relevant Reddit/Discord community. But just to give you something to start with; that thing you're calling a scroll bar is actually the macOS loading bar, it just appears funnily because the display is technically 90 degrees rotated (the Apple logo adheres to the screen rotation you have set in the bios, the loading indicator does not). I also recommend you turn on verbose mode, so you can actually see what's happening and where things get stuck and/or kernel panic. That information will be necessary in figuring out what is going wrong.

I'm not sure what you mean by RAW images, but you might yield better results if you try a clean installation following the information that's out there, rather than an existing installation image, if that's what you were referring to.

Beyond that, I'm afraid I can't be of much use to you, sorry about that. Good luck, though!

**Comment by devisucarmelo** [comment]
Many thanks for your detailed email and for the time you dedicated to me.
I'll try following your suggestions.

Kind regards
DC


Il 29 mar 2023, 05:59 +0200, Dave Jansen ***@***.***>, ha scritto:
