### ISSUE TITLE
USB type A port issue

### ISSUE THREAD

**Issue by cornercat** [hellodeibu/gpd-pocket2-hackintosh#3]
Thanks for the repo and config. I can successfully install 10.14.6.
But there's some weird issue related USB.

- I can only install and boot system through USB-C hub. Can't boot using two type A usb port.
- After installation, for the two type A port, I can only use the right one to connect mouse or usb stick (can't use as boot device). The left one dosen't work. 

I'm using GPD Pocket 2 with m3-7y30 and 8GB ram.

**Comment by balopez83** [comment]
Hi @cornercat , not sure if you're still having issues but I have a temporary solution for you. The EFI that was provided has not yet had its ACPI patched for the USB ports so what is effectively happening is that macOS is cutting off all ports to 15. In a nutshell everything from bluetooth to your mouse to random ports that don't exist on the computer but the chipset supports are activated and the USB 3 doesn't cause its "over" the 15. 

You can solve it 1 of 2 ways:

1. Preferred: create an SSDT patch for your USB, Rehabman has a guide I believe online.
2. Temporary Only: use a "kexts to patch" patch for removing the port limit patch for 10.14.6 you will need I think the 3 by PMHeart and you can find them in the list in Clover Configurator.

If you choose option 2 you may experience other issues, most likely not but it can happen which is why this is not ideal. That said I think you will need to do option 2 anyway prior to option 1 and then after delete the patch. Hope this helps.

**Comment by jibsaram** [comment]
@cornercat @balopez83 apologies for the super late follow-up, I had zero time to work on this until now. I went through the joyful process of creating proper SSDT patches for USB, or I certainly hope they're proper. I tested just about every way I could on my m3-8100y model, and I have all ports working consistently now, even between reboots. 

It would be really great if you could test and confirm this on your end, too.

Cheers!
